### ISSUE TITLE
Slider limit

### ISSUE THREAD

**Issue by valshiv** [MainVirtualizer/CM3D2Editor#1]
Changing the limit for height, shoulders, waist, and hips doesn't affect the model after 100. Also could you add negative values?

**Comment by MainVirtualizer** [comment]
Negative values are available in editor but you need to input the negative sign last, after you enter the magnitude (due to current implementation limit); however, negative values **will not** work, just like the values over 100 as you mentioned. This **cannot** be supported by the editor; my save editor will write the values < 0 or > 100 into the save file but the CM3D2 simply did not recognize them. This is possibly caused by CM3D2's internal logic or limitations of models.
